const ROUTES = [
  {
    id: "rask",
    name: "Den raske løype",
    description: "Den korteste ruten som besøker alle barene i luftlinje.",
    loop: false,
    stops: [
      "Cafe Viking",
      "Cafe Osborne",
      "Under Uret",
      "Restaurant Amalie",
      "Told og Snaps",
      "Eiffel Bar",
      "Cafe Nick",
      "Toga Øl- og Vinstue",
      "Bo-Bi Bar",
      "Jernbanecafeen",
      "Vinstue Halvfems",
      "Alléenberg Bodega",
      "Cafe Intime",
    ],
  },
  {
    id: "rundtur",
    name: "Den runde løype",
    description: "En rundtur som besøker alle barene og fører deg tilbake til der du startet.",
    loop: true,
    stops: [
      "Alléenberg Bodega",
      "Cafe Intime",
      "Cafe Viking",
      "Cafe Osborne",
      "Under Uret",
      "Restaurant Amalie",
      "Told og Snaps",
      "Eiffel Bar",
      "Cafe Nick",
      "Toga Øl- og Vinstue",
      "Bo-Bi Bar",
      "Jernbanecafeen",
      "Vinstue Halvfems",
    ],
  },
  {
    id: "nord-sor",
    name: "Nord til sør",
    description: "En enkel rute som følger barene fra nord til sør.",
    loop: false,
    stops: [
      "Cafe Viking",
      "Cafe Osborne",
      "Under Uret",
      "Restaurant Amalie",
      "Bo-Bi Bar",
      "Told og Snaps",
      "Toga Øl- og Vinstue",
      "Cafe Nick",
      "Cafe Intime",
      "Vinstue Halvfems",
      "Alléenberg Bodega",
      "Eiffel Bar",
      "Jernbanecafeen",
    ],
  },
];

function findRoute(id) {
  return ROUTES.find((route) => route.id === id);
}
